config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'reserves/index'
  get 'reservation/index'
  get 'rooms/index'
  devise_for :users
  root to:'home#index'
  get 'users/show'
  resources :users do
  end
  resources :rooms do
    collection do
      get "search"
    end
  end
  resources :reservations do
    collection do
    post 'confirm'
    end
  end
  resources :reservations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user,optional: true 
  belongs_to :room,optional: true 

  validates :checkin_at, presence: { message: "項目を入力してください" }
  validates :checkout_at, presence: { message: "項目を入力してください" }
  validates :person_count, presence: { message: "項目を入力してください" } , numericality: {only_integer: true, greater_than: 0}

  validate :start_end_check
  validate :day_after_today

  def day_after_today
    unless checkin_at == nil
      errors.add(:checkin_at, 'は、今日を含む過去の日付を入力して下さい') if checkin_at < Date.today
    end
  end

  def start_end_check
    if checkin_at == nil
      errors.add(:checkin_at,"開始日を入力してください")
    elsif checkout_at == nil
      errors.add(:checkout_at,"終了日を入力してください")
    elsif checkout_at < checkin_at
      errors.add(:checkout_at,"終了日は開始日以降の日付にしてください")
    end
  end

  def total_day
    total_day = (checkout_at - checkin_at).to_i
  end

  def total_price
    total_price = (total_day * person_count * room.price)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :reservations
  belongs_to :user,optional: true

  mount_uploader :room_image, RoomImageUploader 

  validates :room_name, :introduction, :address, presence: true
  validates :price , presence: true , numericality: { greater_than_or_equal_to: 0 }

  def self.search(keyword)
    if keyword != ""
      Room.where('room_name LIKE ? OR introduction LIKE ? OR address LIKE ?', "%#{keyword}%", "%#{keyword}%", "%#{keyword}%")
    else
      Room.all
    end
  end

  def self.search(key)
    if key != ""
      Room.where('address LIKE ?', "%#{key}%")
    else
      Room.all
    end
  end

  def self.search(word)
    if word != ""
      Room.where('room_name LIKE ? OR introduction LIKE ?', "%#{word}%",  "%#{word}%")
    else
      Room.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rooms
  has_many :reservations

  validates :name, presence: true, length: { maximum: 20 }
  validates :profile, length: { maximum: 200 }
  validates :email, presence: true
  validates :password, presence: true
  validates :password_confirmation, presence: true

  mount_uploader :User_icon, UserIconUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) 
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
      @user = current_user
    end

    def show
      @user = current_user
    end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @reservations = Reservation.all
  end

  def new
    @user = current_user
    @reservation = Reservation.new

  end

  def search
    @rooms = Room.search(params[:keyword])
  end

  def confirm
    @reservation = Reservation.new(reservation_params)
    @user = current_user
    @room = Room.find(params[:reservation][:room_id])
    if @reservation.checkin_at. == nil
      redirect_to @room, alert:"開始日を入力してください" and return
    end
    if @reservation.checkout_at. == nil
      redirect_to @room, alert:"終了日を入力してください" and return
    end
    if @reservation.checkout_at < @reservation.checkin_at
      redirect_to @room, alert:"終了日は開始日以降の日付にしてください" and return
    end
    if @reservation.person_count == nil
      redirect_to @room, alert:"正しい人数を入力してください" and return
    end
    @total_day = (@reservation.checkout_at - @reservation.checkin_at).to_i 
    @total_price = (@total_day * @reservation.person_count * @room.price)
  end


  def create
    @user = current_user
    @room = Room.find(params[:reservation][:room_id])
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      flash[:notice] = "予約に成功しました"
      redirect_to reservations_path (@reservation)
    else
      flash.now[:alert] = "予約に失敗しました"
      render "rooms/show"
    end
  end

  def show
    @user = current_user
    @reservations = Reservation.all
    @room = @reservation.room
  end

  def edit
    @rooms = Room.all
    @reservation = Reservation.find(params[:id])
  end

  def update
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:notice] = "削除しました"
    redirect_to reservations_path
  end

  def reservation_params
    params.require(:reservation).permit(:checkin_at, :checkout_at, :person_count , :user_id, :room_id , :created_at , :updated_at)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @user = current_user
     @rooms = current_user.rooms
  end

  def search
    @user = current_user
    @rooms = Room.search(params[:keyword])
    @keyword = params[:keyword]
    @rooms = Room.search(params[:key])
    @keyword = params[:key]
    @rooms = Room.search(params[:word])
    @keyword = params[:word]
  end
  
  def new
    @user = current_user
    @room = Room.new
  end
 
  def create
    @user = current_user
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "施設を登録しました"
      redirect_to :rooms
    else
      flash[:notice] = "施設を登録できませんでした"
      render "new"
    end
  end

  def show
    @user = current_user
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
    @room = Room.find(params[:id])
  end
 
  def update
     @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = "宿泊施設を更新しました"
      redirect_to rooms_path
    else
      render :edit
    end
  end
 
  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "ユーザーを削除しました"
    redirect_to rooms_path
  end

  def room_params
    params.require(:room).permit(
      :room_name,
      :room_image,
      :room_image_cache,
      :introduction,
      :price,
      :address
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
 
  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password))
    if @user.save
      redirect_to users_show_path
    else
      render "new"
    end
  end
 
  def show
    @user = current_user
  end
 
  def edit
    @user = User.find(current_user.id)
  end
 
  def update
    @user = User.find(current_user.id)
    if current_user.update(params.require(:user).permit(:User_icon, :name, :profile))
      flash[:notice] = "ユーザーIDが「#{@user.id}」の情報を更新しました"
      redirect_to users_show_path
    else
      flash[:notice] = "ユーザー情報を登録できませんでした"
      render "edit"
    end
  end
 
  def destroy
  end
  
  def user_icon
    send_data(@user.user_icon, disposition: :inline)
  end
end

app/views/home/index.html.erb
<div class="FirstView">
  <section class="container">
    <h2 class="FirstView_title">
      Potepan Shareで<br>
      まだ体験したことのない<br>
      旅をしよう
    </h2>
    <div class="column">
      <div class="box">
        <%= form_with url: search_rooms_path, local: true, method: :get, class: "search-form" do |f| %>
          <%= f.search_field :keyword, placeholder: "エリア名を入力", class: "search-input" %>
          <%= f.submit "検索", class: "search-btn" %>
        <% end %>
      </div>
    </div>
  </section>
</div>

<section class="area">
    <h2 class="Recommend_title">
      おすすめのエリア
    </h2>

    <div class="media">  
      <div class="card">
        <div class="card-content">
          <div class="title-tokyo"><%= link_to '東京都',search_rooms_path(:keyword => "東京") %></div>
        </div>
      </div>

      <div class="card">
        <div class="card-content">
          <div class="title-osaka"><%= link_to '大阪府',search_rooms_path(:keyword => "大阪") %></div>
        </div>
      </div>

      <div class="card">
        <div class="card-content">
           <div class="title-kyoto"><%= link_to '京都府',search_rooms_path(:keyword => "京都") %></div>
        </div>
      </div>

      <div class="card">
        <div class="card-content">
          <div class="title-sapporo"><%= link_to '札幌市',search_rooms_path(:keyword => "札幌") %></div>
        </div>
      </div>
    </div>  

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img class="Navbar__logo" alt="サイトロゴ" src="https://rails-02-sample.herokuapp.com/assets/common/logo.png">
      </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
        <a class="navbar-item"></a>
          <% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
            <% if @user.User_icon?%>
              <p><%= image_tag @user.User_icon.url, class: "icon", style: "border-radius: 30%; width: 50px; height: 50px; object-fit:cover;" %></p>
            <% else %>
              <p><%= image_tag 'https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png',class: "icon", style: "border-radius: 30%; width: 50px; height: 50px; object-fit:cover;" %></p>
            <% end %>
              <strong><%= link_to current_user.name, users_show_path, class: 'point' %></strong>
            <ul class="gnavi__lists">
              <li class="gnavi__list">
                <a href="#">レ</a>
                <ul class="dropdown__lists">
                  <li class="dropdown__list">
                    <a href="#">
                      <%= link_to "施設の新規登録", new_room_path %>
                    </a>
                  </li>
                  <li class="dropdown__list">
                    <a href="#">
                      <%= link_to "予約済み一覧", reservations_path %>
                    </a>
                  </li>
                  <li class="dropdown__list">
                    <a href="#">
                      <%= link_to "登録済み一覧", rooms_path %>
                    </a>
                  </li>
                  <li class="dropdown__list">
                    <a href="#">
                      <%= link_to "アカウント設定", users_show_path %>
                    </a>
                  </li>
                  <li class="dropdown__list">
                    <a href="#">
                      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          <% else %>
            <!-- ユーザーがログインしていなかった時の処理 -->
            <h2> 現在ログインしていません </h2>
            <%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
          <% end %>           
      </div>
    </div>
  </nav>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <hr />
  <%= yield %>
  </body>
</html>

app/views/reservations/confirm.html.erb
<h1>予約の確認</h1>

<%= flash[:notice] %>
<%= flash[:alert] %>


 <table class="table is-fullwidth">
  <tr>
    <th>チェックイン</th>
      <td class="is-right"><%= @reservation.checkin_at.to_s(:datetime_jp) %></td>
    </tr>
    <tr>
      <th>チェックアウト</th>
      <td class="is-right"><%= @reservation.checkout_at.to_s(:datetime_jp) %></td>
    </tr>
    <tr>
      <th>日数</th>
      <td class="is-right"><%= @reservation.total_day %>日</td>
    </tr>
    <tr>
      <th>人数</th>
      <td class="is-right"><%= @reservation.person_count %>人</td>
    </tr>
    <tr>
      <th>お支払い金額</th>
      <td class="is-right"><strong>¥<%= @reservation.total_price.to_s(:delimited) %></strong></td>
    </tr>
  </table>

<%= form_with model: @reservation, url: reservations_path, local: true do |f| %>
  <%= f.hidden_field :user_id, value: @user.id  %>
  <%= f.hidden_field :room_id, value: @room.id %>
  <%= f.hidden_field :checkin_at, value: @reservation.checkin_at %>
  <%= f.hidden_field :checkout_at, value: @reservation.checkout_at %>
  <%= f.hidden_field :person_count, value: @reservation.person_count %>
  <%= f.hidden_field :total_price, value: @reservation.total_price %>

  <p>上記内容でよろしければ「予約を確定」を押してください。</p>
    <div class= "submit is-fullwidth">
      <%= f.submit "予約を確定", class: "button is-primary is-fullwidth" %>
    </div>
    <div class= "back is_fullwidth">
      <%=link_to 'キャンセル', :back, class: "button is-fullwidth" %>
    </div>
<% end %>

app/views/reservations/index.html.erb
<h3>予約済み施設一覧</h3>

<section class="section">
  <table class="reservation_ichiran">
    <thead>
        <tr>
        <th>施設画面</th>
        <th>施設名</th>
        <th>施設紹介</th>
        <th>合計金額</th>
        <th>チェックイン日</th>
        <th>チェックアウト日</th>
        <th>予約確定日時</th>
        <th>削除</th>
        </tr>
    </thead>
    <tbody>
    <% if @reservations.count > 0 %>
      <% @reservations.each do |reservation| %>
        <tr>
          <td><% if reservation.room.room_image?%>
                <p><%= image_tag reservation.room.room_image.url, class: "icon", style: "width: 200px; height: 100px; object-fit:cover;" %></p>
              <% else %>
                <p><%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png',class: "icon", style: "width: 200px; height: 100px; object-fit:cover;" %></p>
              <% end %></td>      
          <td><%= reservation.room.room_name %></td>
          <td><%= reservation.room.introduction %></td>
          <td>¥<%= reservation.total_price.to_s(:delimited) %></td>
          <td><%= reservation.checkin_at.to_s(:datetime_jp) %></td>
          <td><%= reservation.checkout_at.to_s(:datetime_jp) %></td>
          <td><%= reservation.created_at.to_s(:datetime_jp_detail) %></td>
          <td>
            <%= button_to "予約を削除" , reservation , method: :delete , data: { comfilm: "本当に削除しますか？" } %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <td colspan="9">現在登録している施設はありません</td>
    <% end %>
    </tbody>
  </table>
</section>

app/views/reservations/show.html.erb
<h2>予約済み施設一覧</h2>
<table>
  <thead>
    <tr>
      <th>施設名</th>
      <th>施設紹介</th>
      <th>合計金額</th>
      <th>チェックイン日</th>
      <th>チェックアウト日</th>
      <th>予約確定日時</th>
    </tr>
  </thead>
  <tbody>
  <% if @reservation == true %>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.room.room_name %></td>
        <td><%= reservation.room.introduction %></td>
        <td>¥<%= reservation.total_price.to_s(:delimited) %></td>
        <td><%= reservation.checkin_at.created_at.to_s(:datetime_jp) %></td>
        <td><%= reservation.checkout_at.created_at.to_s(:datetime_jp) %></td>
        <td><%= reservation.created_at.created_at.to_s(:datetime_jp_detail) %></td>
        <td>
          <%= link_to "予約を削除" , reservation , method: :delete , data: { comfilm: "本当に削除しますか？" } %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <td>現在登録している施設はありません</td>
  <% end %>
  </tbody>
</table>

app/views/rooms/index.html.erb
<h3>登録済み施設一覧</h3>

 <table>
   <thead>
     <tr>
      <th>施設画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>宿泊料金</th>
      <th>作成日</th>
      <th>施設詳細</th>
      <th>削除</th>
     </tr>
   </thead>

   <tbody>
     <% @rooms.each do |room| %>
       <tr>
        <td>
          <% if room.room_image?%>
            <p><%= image_tag room.room_image.url, class: "icon", style: "width: 100px; height: 100px; object-fit:cover;" %></p>
          <% else %>
            <p><%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png',class: "icon", style: "width: 100px; height: 100px; object-fit:cover;" %></p>
          <% end %>
        </td>
        <td><%= room.room_name %></td>
        <td><%= room.introduction %></td>
        <td><%= room.price.to_s(:delimited) %></td>
        <td><%= room.created_at.to_s(:datetime_jp) %></td>
        <td><%= link_to "詳細" , room_path(room) %></td>
        <td><%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
       </tr>
     <% end %>
   </tbody>
 </table>

<div class= "newroom">
  <%= link_to "新しい部屋の登録" , new_room_path %>
</div>

app/views/rooms/new.html.erb
<h3>新規施設登録</h3>

 <%= form_with model: @room do |f| %>
   <table>
     <tr>
       <th><%= f.label :room_image ,"施設画像" %></th>
       <td>
        <%= f.file_field :room_image, accept: 'image/*', onchange: 'previewImage(preview)' %>
        <%= f.hidden_field :room_image_cache %>
       </td>
     </tr>

     <tr>
       <th><%= f.label :room_name ,"施設名" %></th>
       <td><%= f.text_field :room_name %></td>
     </tr>

     <tr>
       <th><%= f.label :introduction ,"紹介文" %></th>
       <td><%= f.text_area :introduction %></td>
     </tr>

     <tr>
       <th><%= f.label :price ,"料金" %></th>
       <td><%= f.number_field :price , min:1 %></td>
     </tr>
     <tr>
       <th><%= f.label :address ,"住所" %></th>
       <td><%= f.text_field :address %></td>
     </tr>
   </table>

   <div>
     <ul>
       <li><%= f.submit "登録完了する"%></li>
       <li><%= link_to "キャンセル",:back, class: "button" %></li>
     </ul>
   </div>
 <% end %>

app/views/rooms/search.html.erb
<h2>検索結果：<%= @rooms.count %>件</h2>
  <div class="box">
    <%= form_with url: search_rooms_path, local: true, method: :get, class: "search-form" do |f| %>
      <%= f.search_field :key, placeholder: "エリア名を入力", class: "search-input-i" %>
      <%= f.search_field :word, placeholder: "キーワード名を入力", class: "search-input-b" %>
      <%= f.submit "検索", class: "search-btn-i" %>
    <% end %>
  </div>

  <tbody>
    <ul class="roomlist">
    <% if @rooms.count > 0 %>
      <% @rooms.each do |room| %>
          <li class="roomlist-list">
            <div class="room_image">
              <% if room.room_image?%>
                <p><%= image_tag room.room_image.url, class: "icon", style: "width: 300px; height: 200px; object-fit:cover;" %></p>
              <% else %>
                <p><%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png',class: "icon", style: "width: 300px; height: 200px; object-fit:cover;" %></p>
              <% end %>
            </div>
            <div class="roomlist-list">
              <p class><%= room.room_name %></p>
              <p class="roomlist-list-in"><%= room.introduction %></p>
              <p class><%= room.price.to_s(:delimited) %></p>
              <p class><%= room.address %></p>
              <p><%= link_to "詳細はこちら", room_path(room), class: "roomlist-link" %></p>
            </div>
          </li>
      <% end %>
    <% else %>
      <td colspan="9">現在登録している施設はありません</td>
    <% end %>
    </ul>  
  </tbody>

app/views/rooms/show.html.erb
<h3>新規予約</h3>

<div class="back-button">
  <%= link_to "← 戻る",:back %>
</div>

<ul class="roomlist">
    <li class="roomlist-list">
      <div class="room_image">
        <% if @room.room_image?%>
          <p><%= image_tag @room.room_image.url, class: "icon", style: "width: 300px; height: 200px; object-fit:cover;" %></p>
        <% else %>
          <p><%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png',class: "icon", style: "width: 300px; height: 200px; object-fit:cover;" %></p>
        <% end %>
      </div>
    </li>
    <li class="roomlist-list">  
        <p class><%= @room.room_name %></p>
        <p class="roomlist-list-in"><%= @room.introduction %></p>
        <p class><%= @room.price.to_s(:delimited) %></p>
        <p class><%= @room.address %></p>

<%= form_with model: @reservation, method: :post , url: confirm_reservations_path, local: true do |f| %>
  <table>
    <tr>
      <th><%= f.label :checkin ,"チェックイン日" %></th>
      <td><%= f.date_field :checkin_at%></td>
    </tr>
    <tr>
      <th><%= f.label :checkout ,"チェックアウト日" %></th>
      <td><%= f.date_field :checkout_at %></td>
    </tr>
    <tr>
      <th><%= f.label :number_of_people ,"人数" %></th>
      <td><%= f.number_field :person_count, min:1, :placeholder => "0人" %></td>
    </tr>
  </table>

  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.hidden_field :room_id, value: @room.id %>

<div>
  <%= f.submit "予約確認画面へ" %>
</div>
  </li>
</ul>
 <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            <img class="Navbar__logo" alt="サイトロゴ" src="https://rails-02-sample.herokuapp.com/assets/common/logo.png">
        </a>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <div class="navbar-item">
            </div>
        </div>
        <div class="navbar-end">
            <a class="navbar-item"></a>
            <a class="navbar-item"></a>
            <!-- もしログインしていなかったら-->
            <% if (!user_signed_in?) %>
                <div class="navbar-item">
                    <div class="buttons">
                        <%= link_to  "ログイン", new_user_session_path, class: "button is-white" %>
                        <%= link_to  "新規登録", new_user_registration_path, class: "button is-white" %>
                    </div>
                </div>
            <!-- ログインしていたら-->
            <% else %>
                <div class="navbar-item has-dropdown is-hoverable" style="margin-right: 100px;">
                    <a class="navbar-item"><%= current_user.email %></a>
                    <div class="navbar-dropdown">
                        <a href="" class="navbar-item"></a>
                        <a href="" class="navbar-item"></a>
                        <hr class="navbar-divider">
                        <%= link_to  "ログアウト", destroy_user_session_path, method: :delete, class: "navbar-item" %>
                    </div>
                </div>
            <% end %>            
        </div>
    </div>
</nav>
<script>
$(document).ready(function() {
  // navbar burgerアイコンでクリックイベントを確認する
  $(".navbar-burger").click(function() {
      // 「navbar-burger」と「navbar-menu」の両方で「is-active」クラスを切り替える
      $(".navbar-burger").toggleClass("is-active");
      $(".navbar-menu").toggleClass("is-active");
  });
});
</script>

app/views/users/edit.html.erb
<h3>ユーザー編集</h3>

 <%= form_with model: @user do |f| %>
   <table>
     <tr>
        <th><%= f.label :user_icon,"アイコン画像" %></th>
        <td>
         <%= f.file_field :User_icon, accept: 'image/*', onchange: 'previewImage(preview)' %>
        <%= f.hidden_field :User_icon_cache %>
        </td>
     </tr>
     <tr>
       <th><%= f.label :name ,"名前" %></th>
       <td><%= f.text_field :name %></td>
     </tr>
     <tr>
       <th><%= f.label :profile ,"自己紹介" %></th>
       <td><%= f.text_area :profile %></td>
     </tr>
   </table>

   <div>
     <ul>
       <li><%= f.submit "編集を完了する" %></li>
     </ul>
   </div>
 <% end %>

app/views/users/show.html.erb
<h3>プロフィール</h3>

 <table>
  <tr>
    <th>アイコン画像</th>
     <td>
        <% if @user.User_icon?%>
          <p><%= image_tag @user.User_icon.url, class: "icon", style: "border-radius: 30%; width: 50px; height: 50px; object-fit:cover;" %></p>
        <% else %>
          <p><%= image_tag 'https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png',class: "icon", style: "border-radius: 30%; width: 50px; height: 50px; object-fit:cover;" %></p>
        <% end %>
     </td>
  </tr>
  <tr>   
     <th>名前</th>
     <td><%= @user.name %></td>
  </tr>
  <tr>
     <th>メールアドレス</th>
     <td><%= @user.email %></td>
  </tr>
  <tr>
     <th>パスワード</th>
     <td>********</td>
  </tr>
  <tr>
     <th>自己紹介</th>
     <td><%=  @user.profile %></td>
  </tr>
 </table>

 <div>
   <ul>
     <li><%= link_to "編集", edit_user_path(current_user), class: "button is-primary" %></li>
   </ul>
   <ul>
      <%= link_to "アカウント編集", edit_user_registration_path, class: "button is-primary" %>
   </ul>
 </div>